import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compileFromFile } from "json-schema-to-typescript";

const scriptRoot = dirname(fileURLToPath(import.meta.url));
const contractRoot = resolve(scriptRoot, "..");
const repoRoot = resolve(contractRoot, "../..");
const schemaRoot = resolve(contractRoot, "schemas");
const generatedRoot = resolve(contractRoot, "src/generated");
const pythonRoot = resolve(repoRoot, "src/mycli/schemas/generated");
const check = process.argv.includes("--check");
const banner = "// Generated by packages/contracts/scripts/generate.mjs. Do not edit.\n";

async function writeOrCheck(path, content, check) {
	const normalized = content.replaceAll("\r\n", "\n").replace(/\s+$/, "") + "\n";
	if (check) {
		const current = await readFile(path, "utf8").catch(() => "");
		if (current !== normalized) {
			throw new Error(`Generated contract drift: ${relative(repoRoot, path)}`);
		}
		return;
	}
	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, normalized, "utf8");
}

const targets = [
	["catalog.schema.json", "catalog.ts"],
	["json-rpc.schema.json", "json-rpc-message.ts"],
	["gateway-events.schema.json", "gateway-event-notification.ts"],
];

for (const [schemaName, outputName] of targets) {
	const generated = await compileFromFile(resolve(schemaRoot, schemaName), {
		bannerComment: "",
		cwd: schemaRoot,
		unknownAny: false,
	});
	await writeOrCheck(resolve(generatedRoot, outputName), banner + generated, check);
}

for (const name of ["catalog.json", "gateway-events.schema.json"]) {
	const content = await readFile(resolve(schemaRoot, name), "utf8");
	await writeOrCheck(resolve(pythonRoot, name), content, check);
}
