from __future__ import annotations

_SLASH_COMMANDS: tuple[str, ...] = (
    "/help",
    "/status",
    "/status usage",
    "/status context",
    "/status stats",
    "/view",
    "/view default",
    "/view verbose",
    "/view focus",
    "/session",
    "/session list",
    "/session resume <session>",
    "/session fork [source] <new-session> [message-index]",
    "/session search <query>",
    "/session maintenance",
    "/session maintenance --apply-empty",
    "/session maintenance --apply-orphans",
    "/session maintenance --apply-vacuum",
    "/quit",
    "/tools",
    "/tools sets",
    "/tools permissions",
    "/tools hooks",
    "/tools extensions",
    "/tools plugins",
    "/tools plugins <plugin_id> <command_name>",
    "/tools skills",
    "/agents",
    "/agents list",
    "/agents inspect <profile_id>",
    "/agents runs",
    "/agents runs <child_session_id>",
    "/agents kill",
    "/tasks",
    "/tasks agents",
    "/tasks agents <child_session_id>",
    "/tasks agents kill <child_session_id>",
    "/tasks bashes",
    "/tasks kill-agents",
    "/changes",
    "/changes undo",
    "/undo",
    "/plan",
    "/memory",
    "/trace",
    "/trace export",
    "/trace logs",
    "/clear",
    "/theme",
    "/mark <name>",
    "/release-notes",
)


def slash_command_candidates() -> tuple[str, ...]:
    return _SLASH_COMMANDS
