import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compileFromFile } from "json-schema-to-typescript";

const scriptRoot = dirname(fileURLToPath(import.meta.url));
const contractRoot = resolve(scriptRoot, "..");
const repoRoot = resolve(contractRoot, "../../..");
const schemaRoot = resolve(contractRoot, "schemas");
const generatedRoot = resolve(contractRoot, "src/generated");
const check = process.argv.includes("--check");
const banner = "// Generated by backend/packages/contracts/scripts/generate.mjs. Do not edit.\n";

async function writeOrCheck(path, content, check) {
	const normalized = content.replaceAll("\r\n", "\n").replace(/\s+$/, "") + "\n";
	if (check) {
		const current = await readFile(path, "utf8").catch(() => "");
		if (current !== normalized) {
			throw new Error(`Generated contract drift: ${relative(repoRoot, path)}`);
		}
		return;
	}
	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, normalized, "utf8");
}

const targets = [
	["error-context.schema.json", "error-context.ts"],
	["catalog.schema.json", "catalog.ts"],
	["json-rpc.schema.json", "json-rpc-message.ts"],
	["gateway-tool-record.schema.json", "gateway-tool-record.ts"],
	["gateway-events.schema.json", "gateway-event-notification.ts"],
	["gateway-rpc.schema.json", "gateway-rpc.ts"],
	["mcp-elicitation.schema.json", "mcp-elicitation.ts"],
	["runtime-turn.schema.json", "runtime-turn-record.ts"],
	["provider-attempt.schema.json", "provider-attempt.ts"],
	["runtime-state.schema.json", "runtime-state-record.ts"],
	["plugin-v2-manifest.schema.json", "plugin-v2-manifest.ts"],
	["plugin-v2-protocol.schema.json", "plugin-v2-protocol.ts"],
];

for (const [schemaName, outputName] of targets) {
	const generated = await compileFromFile(resolve(schemaRoot, schemaName), {
		bannerComment: "",
		cwd: schemaRoot,
		unknownAny: schemaName === "gateway-rpc.schema.json",
		...(schemaName === "error-context.schema.json" ? { additionalProperties: false, ignoreMinAndMaxItems: true } : {}),
	});
	await writeOrCheck(resolve(generatedRoot, outputName), banner + generated, check);
}
