import type { Provider } from "@earendil-works/pi-ai";

// Module wiring only. Models, protocols, and authentication remain SDK-owned.
// The directory parity test catches SDK additions and renamed factories.
export const PI_AI_PROVIDER_LOADERS: ReadonlyMap<string, () => Promise<Provider>> = new Map<string, () => Promise<Provider>>([
	["amazon-bedrock", async () => (await import("@earendil-works/pi-ai/providers/amazon-bedrock")).amazonBedrockProvider()],
	["ant-ling", async () => (await import("@earendil-works/pi-ai/providers/ant-ling")).antLingProvider()],
	["anthropic", async () => (await import("@earendil-works/pi-ai/providers/anthropic")).anthropicProvider()],
	["azure-openai-responses", async () => (await import("@earendil-works/pi-ai/providers/azure-openai-responses")).azureOpenAIResponsesProvider()],
	["baseten", async () => (await import("@earendil-works/pi-ai/providers/baseten")).basetenProvider()],
	["cerebras", async () => (await import("@earendil-works/pi-ai/providers/cerebras")).cerebrasProvider()],
	["cloudflare-ai-gateway", async () => (await import("@earendil-works/pi-ai/providers/cloudflare-ai-gateway")).cloudflareAIGatewayProvider()],
	["cloudflare-workers-ai", async () => (await import("@earendil-works/pi-ai/providers/cloudflare-workers-ai")).cloudflareWorkersAIProvider()],
	["deepseek", async () => (await import("@earendil-works/pi-ai/providers/deepseek")).deepseekProvider()],
	["fireworks", async () => (await import("@earendil-works/pi-ai/providers/fireworks")).fireworksProvider()],
	["github-copilot", async () => (await import("@earendil-works/pi-ai/providers/github-copilot")).githubCopilotProvider()],
	["google", async () => (await import("@earendil-works/pi-ai/providers/google")).googleProvider()],
	["google-vertex", async () => (await import("@earendil-works/pi-ai/providers/google-vertex")).googleVertexProvider()],
	["groq", async () => (await import("@earendil-works/pi-ai/providers/groq")).groqProvider()],
	["huggingface", async () => (await import("@earendil-works/pi-ai/providers/huggingface")).huggingfaceProvider()],
	["kimi-coding", async () => (await import("@earendil-works/pi-ai/providers/kimi-coding")).kimiCodingProvider()],
	["minimax", async () => (await import("@earendil-works/pi-ai/providers/minimax")).minimaxProvider()],
	["minimax-cn", async () => (await import("@earendil-works/pi-ai/providers/minimax-cn")).minimaxCnProvider()],
	["mistral", async () => (await import("@earendil-works/pi-ai/providers/mistral")).mistralProvider()],
	["moonshotai", async () => (await import("@earendil-works/pi-ai/providers/moonshotai")).moonshotaiProvider()],
	["moonshotai-cn", async () => (await import("@earendil-works/pi-ai/providers/moonshotai-cn")).moonshotaiCnProvider()],
	["nvidia", async () => (await import("@earendil-works/pi-ai/providers/nvidia")).nvidiaProvider()],
	["openai", async () => (await import("@earendil-works/pi-ai/providers/openai")).openaiProvider()],
	["openai-codex", async () => (await import("@earendil-works/pi-ai/providers/openai-codex")).openaiCodexProvider()],
	["opencode", async () => (await import("@earendil-works/pi-ai/providers/opencode")).opencodeProvider()],
	["opencode-go", async () => (await import("@earendil-works/pi-ai/providers/opencode-go")).opencodeGoProvider()],
	["openrouter", async () => (await import("@earendil-works/pi-ai/providers/openrouter")).openrouterProvider()],
	["qwen-token-plan", async () => (await import("@earendil-works/pi-ai/providers/qwen-token-plan")).qwenTokenPlanProvider()],
	["qwen-token-plan-cn", async () => (await import("@earendil-works/pi-ai/providers/qwen-token-plan-cn")).qwenTokenPlanCnProvider()],
	["qwen-token-plan-individual", async () => (await import("@earendil-works/pi-ai/providers/qwen-token-plan-individual")).qwenTokenPlanIndividualProvider()],
	["radius", async () => (await import("@earendil-works/pi-ai/providers/radius")).radiusProvider()],
	["together", async () => (await import("@earendil-works/pi-ai/providers/together")).togetherProvider()],
	["vercel-ai-gateway", async () => (await import("@earendil-works/pi-ai/providers/vercel-ai-gateway")).vercelAIGatewayProvider()],
	["xai", async () => (await import("@earendil-works/pi-ai/providers/xai")).xaiProvider()],
	["xiaomi", async () => (await import("@earendil-works/pi-ai/providers/xiaomi")).xiaomiProvider()],
	["xiaomi-token-plan-ams", async () => (await import("@earendil-works/pi-ai/providers/xiaomi-token-plan-ams")).xiaomiTokenPlanAmsProvider()],
	["xiaomi-token-plan-cn", async () => (await import("@earendil-works/pi-ai/providers/xiaomi-token-plan-cn")).xiaomiTokenPlanCnProvider()],
	["xiaomi-token-plan-sgp", async () => (await import("@earendil-works/pi-ai/providers/xiaomi-token-plan-sgp")).xiaomiTokenPlanSgpProvider()],
	["zai", async () => (await import("@earendil-works/pi-ai/providers/zai")).zaiProvider()],
	["zai-coding-cn", async () => (await import("@earendil-works/pi-ai/providers/zai-coding-cn")).zaiCodingCnProvider()],
]);
